### ISSUE TITLE
Add test vectors

### ISSUE THREAD

**Issue by joebandenburg** [joebandenburg/libaxolotl-javascript#5]
We should have some tests that use specific inputs and compare the output with known values derived from another working implementation. This will help prove that the implementation is correct and compatible with other implementations. This should be done both at the API level and the unit level.

A challenge for this testing approach is the need to use the correct cryptographic primitives, including Curve25519.

**Comment by CharlesOkwuagwu** [comment]
I have used the existing tests from other implementations like you mentioned.
Sadly these are quite few.
