### ISSUE TITLE
Please confirm if your code is correct below: Should it be a agreements.push or agreements.concat ?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [joebandenburg/libaxolotl-javascript#7]
SessionFactory line 151:

```
    if (parameters.sessionVersion >= 3 && parameters.theirOneTimePreKey) {
        agreements.push(crypto.calculateAgreement(parameters.theirOneTimePreKey,
            parameters.ourBaseKeyPair.private));
    }
```

Should it be a agreements.push or agreements.concat ?

Are you adding to the end of agreements or the beginning?

Please compare with other implementations.

**Comment by joebandenburg** [comment]
I believe this is correct. We're pushing onto the array of agreements. It is an array of `ArrayBuffer`s. The one time pre key is the 4th and final agreement. 

See https://github.com/WhisperSystems/libaxolotl-android/blob/master/java/src/main/java/org/whispersystems/libaxolotl/ratchet/RatchetingSession.java#L89 for comparison.

I have confirmed that my implementation does indeed establish a session correctly with other implementations.

**Comment by CharlesOkwuagwu** [comment]
ok cool
