### ISSUE TITLE
Please correct the documentation:Verify an Ed25519 signature Parameters 

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [joebandenburg/libaxolotl-javascript#8]
https://github.com/joebandenburg/libaxolotl-javascript/blob/master/doc/crypto.md

Name    Type    Description
**privateKey**  ArrayBuffer The 33 byte public half of the key used to produce the signature.

Should be publicKey

**Comment by joebandenburg** [comment]
Good spot. Thanks.

**Comment by CharlesOkwuagwu** [comment]
yup

**Comment by CharlesOkwuagwu** [comment]
Question,

How do we know when to use the 33-byte vs 32 byte length Public keys?

**Comment by joebandenburg** [comment]
All the public keys on the crypto interface should be 33-byte. It's an error if it says 32-byte anywhere.

**Comment by CharlesOkwuagwu** [comment]
I'm just curious.
We might have 32 byte "theirXXX" Public keys in hand.
Do we just pre-pend 0x05 to this?

**Comment by CharlesOkwuagwu** [comment]
calculateAgreement(theirEphemeralPublicKey As Byte(), ourEphemeralPrivateKey As Byte())

I guess it would make sense to always check theirEphemeralPublicKey.Length=33 and add prefix with 0x05 otherwise

**Comment by CharlesOkwuagwu** [comment]
@ All the public keys on the crypto interface should be 33-byte. It's an error if it says 32-byte anywhere.

This may not be true for **verifySignature**

`verifySignature(publicKey, dataToSign, purportedSignature)`

publicKey here is the 32-byte variant without the leading 0x05
